Repository if-muneo/muneo-be, pull requests merged in 2025-06, with the labels that each got.

#2 Mun 16 패키지 구조 세팅 및 코드 합치기
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/ureca/muneobe/common/auth/entity/Member.java
  src/main/java/ureca/muneobe/common/chat/CustomHandshakeHandler.java
  src/main/java/ureca/muneobe/common/chat/UserHandshakeInterceptor.java
  src/main/java/ureca/muneobe/common/chat/config/WebSocketConfig.java
  src/main/java/ureca/muneobe/common/chat/config/openai/OpenAIWebClientConfig.java
  src/main/java/ureca/muneobe/common/chat/config/openai/OpenAiFirstPrompt.java
  src/main/java/ureca/muneobe/common/chat/config/openai/OpenAiSecondPrompt.java
  src/main/java/ureca/muneobe/common/chat/controller/ChatController.java
  src/main/java/ureca/muneobe/common/chat/dto/ChatRequest.java
  src/main/java/ureca/muneobe/common/chat/dto/ChatResponse.java
  src/main/java/ureca/muneobe/common/chat/entity/Addon.java
  src/main/java/ureca/muneobe/common/chat/entity/AddonAddonGroup.java
  src/main/java/ureca/muneobe/common/chat/entity/AddonGroup.java
  src/main/java/ureca/muneobe/common/chat/entity/AddonType.java
  src/main/java/ureca/muneobe/common/chat/entity/Chat.java
  src/main/java/ureca/muneobe/common/chat/entity/Combined.java
  src/main/java/ureca/muneobe/common/chat/entity/CombinedGroup.java
  src/main/java/ureca/muneobe/common/chat/entity/CombinedType.java
  src/main/java/ureca/muneobe/common/chat/entity/DataType.java
  src/main/java/ureca/muneobe/common/chat/entity/Fat.java
  src/main/java/ureca/muneobe/common/chat/entity/Mplan.java
  src/main/java/ureca/muneobe/common/chat/entity/MplanDetail.java
  src/main/java/ureca/muneobe/common/chat/entity/MplanType.java
  src/main/java/ureca/muneobe/common/chat/entity/Qualification.java
  src/main/java/ureca/muneobe/common/chat/entity/Review.java
  src/main/java/ureca/muneobe/common/chat/entity/Subscription.java
  src/main/java/ureca/muneobe/common/chat/repository/ChatRedisRepository.java
  src/main/java/ureca/muneobe/common/chat/service/ChatService.java
  src/main/java/ureca/muneobe/common/common/BaseEntity.java
  src/main/java/ureca/muneobe/common/openai/OpenAiClient.java
  src/main/java/ureca/muneobe/common/openai/dto/IntentJson.java
  src/main/java/ureca/muneobe/common/openai/dto/Message.java
  src/main/java/ureca/muneobe/common/openai/dto/OpenAiRequest.java
  src/main/java/ureca/muneobe/common/openai/dto/OpenAiResponse.java
  src/main/java/ureca/muneobe/config/OpenAIConfig.java
  src/main/java/ureca/muneobe/controller/Demo.java
  src/main/java/ureca/muneobe/demo/DemoController.java
  src/main/java/ureca/muneobe/global/exception/GlobalException.java
  src/main/java/ureca/muneobe/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/ureca/muneobe/global/response/ErrorCode.java
  src/main/java/ureca/muneobe/global/response/ResponseBody.java
  src/main/resources/application.properties
  src/main/resources/static/client.html
Labels: ✨Feature

#5 MUN-22 feat: vectorDB 임베딩 값 삽입, 조회 기능 구현
  build.gradle
  src/main/java/ureca/muneobe/common/vector/controller/MobilePlanController.java
  src/main/java/ureca/muneobe/common/vector/dto/RecommendationRequest.java
  src/main/java/ureca/muneobe/common/vector/embedding/EmbeddingSentence.java
  src/main/java/ureca/muneobe/common/vector/entity/Fat.java
  src/main/java/ureca/muneobe/common/vector/repository/FatJdbcRepository.java
  src/main/java/ureca/muneobe/common/vector/repository/FatRepository.java
  src/main/java/ureca/muneobe/common/vector/service/FatService.java
Labels: ✨Feature

#9 MUN-26 feat: 1차 프롬프트 dto 구현
  src/main/java/ureca/muneobe/common/chat/config/openai/OpenAiFirstPrompt.java
  src/main/java/ureca/muneobe/common/chat/config/openai/OpenAiSecondPrompt.java
  src/main/java/ureca/muneobe/common/chat/service/ChatService.java
  src/main/java/ureca/muneobe/common/openai/OpenAiClient.java
  src/main/java/ureca/muneobe/common/openai/dto/IntentJson.java
  src/main/java/ureca/muneobe/common/openai/dto/router/DailyResponse.java
  src/main/java/ureca/muneobe/common/openai/dto/router/FirstPromptResponse.java
  src/main/java/ureca/muneobe/common/openai/dto/router/InappropriateResponse.java
  src/main/java/ureca/muneobe/common/openai/dto/router/RdbResponse.java
  src/main/java/ureca/muneobe/common/openai/dto/router/VectorResponse.java
  src/main/java/ureca/muneobe/global/response/ErrorCode.java
  src/main/resources/application.yml
Labels: ✨Feature

#15 Mun 39 로그인 cors해결
  src/main/java/ureca/muneobe/common/auth/config/WebConfig.java
  src/main/java/ureca/muneobe/common/auth/interceptor/LoginInterceptor.java
  src/main/java/ureca/muneobe/common/auth/service/MemberService.java
Labels: ⚔ Hotfix

#26 MUN-44 refactor: 배포 서버 url 에 맞춰 cors 설정
  src/main/java/ureca/muneobe/common/auth/config/CorsProperties.java
  src/main/java/ureca/muneobe/common/auth/config/WebConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 🌟 Refector

#51 MUN-61 feat:addon 수정완료
  src/main/java/ureca/muneobe/common/addongroup/dto/response/AddonGroupAddonsResponse.java
  src/main/java/ureca/muneobe/common/addongroup/service/AddonGroupService.java
  src/test/java/ureca/muneobe/common/addongroup/controller/AddonGroupControllerTest.java
Labels: ⚔ Hotfix
